# https://github.com/luizdepra/hugo-coder/blob/main/docs/configurations.md#complete-example
baseURL: 'https://anshumantripathi.com/'
languageCode: 'en-us'
title: 'Anshuman Tripathi'
theme: 'hugo-coder'
defaultcontentlanguage: "en"
paginate: 20
pygmentsstyle: "bw"
pygmentscodefences: true
pygmentscodefencesguesssyntax: true
enableEmoji: true
enableGitInfo: true
customSCSS: ["scss/_footer.scss"]
author:
  name: Anshuman Tripathi

menu:
  main:
    - name: "Blog"
      weight: 1
      url: "blog/"
    - name: "Series"
      weight: 3
      url: "series/"
    - name: "Projects"
      weight: 4
      url: "projects/"
    - name: "About"
      weight: 5
      url: "about/"
    - name: "Search"
      weight: 6
      url: "search/"

taxonomies:
  category: "categories"
  tag: "tags"
  series: "series"

# Set Goldmark markup
# https://gohugo.io/getting-started/configuration-markup/#configure-markup
markup:
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      linkifyProtocol: https
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute:
        block: false
        title: true
      autoHeadingID: true
      autoHeadingIDType: github
      wrapStandAloneImageWithinParagraph: true
    renderer:
      # By default, Goldmark ignores newlines within a paragraph. Set to true to render newlines as <br> elements.
      hardWraps: true
      unsafe: true
      xhtml: false

  highlight:
    anchorLineNos: false
    codeFences: true
    guessSyntax: true
    hl_Lines: ""
    hl_inline: false
    lineAnchors: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    noHl: false
    style: dracula
    tabWidth: 2

  tableOfContents:
    endLevel: 3
    ordered: false
    startLevel: 2
