# https://github.com/luizdepra/hugo-coder/blob/main/docs/configurations.md#complete-example
baseURL: 'https://anshumantripathi.com/'
languageCode: 'en-us'
title: 'Anshuman Tripathi'
theme: 'hugo-coder'
defaultcontentlanguage: "en"
paginate: 20
pygmentsstyle: "bw"
pygmentscodefences: true
pygmentscodefencesguesssyntax: true

params:
  author: "Anshuman Tripathi"
  info: "Platform and DevOps Engineering"
  description: "Hi, I am Anshuman Tripathi"
  keywords: "blog,developer,personal"
  colorScheme: "auto"
  avatarurl: "images/avatar.png"

  social:
    - name: Github
      icon: "fa fa-github fa-2x"
      weight: 1
      url: "https://github.com/AnshumanTripathi/"
    - name: Twitter
      icon: "fa fa-twitter fa-2x"
      weight: 2
      url: "https://twitter.com/anshumant09/"
    - name: LinkedIn
      icon: "fa fa-linkedin fa-2x"
      weight: 2
      url: "https://www.linkedin.com/in/anshumantripathi09/"

  goatCounter:
    code: "anshumantripathi"

menu:
  main:
    - name: "Samyak"
      weight: 1
      url: "samyak/"
    - name: "About"
      weight: 2
      url: "about/"

taxonomies:
  category: "categories"
  tag: "tags"

# Set Goldmark markup
# https://gohugo.io/getting-started/configuration-markup/#configure-markup
markup:
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      linkifyProtocol: https
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute:
        block: false
        title: true
      autoHeadingID: true
      autoHeadingIDType: github
      wrapStandAloneImageWithinParagraph: true
    renderer:
      # By default, Goldmark ignores newlines within a paragraph. Set to true to render newlines as <br> elements.
      hardWraps: true
      unsafe: false
      xhtml: false

  highlight:
    anchorLineNos: false
    codeFences: true
    guessSyntax: true
    hl_Lines: ""
    hl_inline: false
    lineAnchors: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    noHl: false
    style: dracula
    tabWidth: 2

  tableOfContents:
    endLevel: 3
    ordered: false
    startLevel: 2
