[build]
publish = "public"
command = "make build-production"

[build.environment]
HUGO_VERSION = "0.133.0"

[context.production.environment]
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.deploy-preview]
command = "make build-production"
