[build]
    publish = "public"
    command = "make build-production"

    [build.environment]
        HUGO_VERSION = "0.136.2"

[context.production.environment]
  HUGO_ENV           = "production"
  HUGO_ENABLEGITINFO = "true"

[context.deploy-preview]
  command = "make build-production"
