author: "Anshuman Tripathi"
info: "Platform and DevOps Engineering"
description: "Hi, I am Anshuman Tripathi"
keywords: "blog,developer,personal"
colorScheme: "auto"
avatarurl: "images/me.jpeg"
favicon_16: "images/favicon-face.png"
favicon_32: "images/favicon-face.png"
since: 2023
commit: "https://github.com/AnshumanTripathi/anshumantripathi.github.io/commits/"
license: apache

social:
  - name: Github
    icon: "fa fa-github fa-2x"
    weight: 1
    url: "https://github.com/AnshumanTripathi/"
  - name: LinkedIn
    icon: "fa fa-linkedin fa-2x"
    weight: 2
    url: "https://www.linkedin.com/in/anshumantripathi09/"
  - name: Medium
    icon: "fa fa-2x fa-medium"
    weight: 3
    url: "https://medium.com/@anshumantripathi"
  - name: "Mastadon"
    icon: "fa-brands fa-2x fa-mastodon"
    weight: 4
    url: "https://hachyderm.io/@anshuman"
  - name: "Bluesky"
    icon: "fa-brands fa-2x fa-bluesky"
    weight: 5
    url: "https://bsky.app/profile/anshumantripathi.bsky.social"
  - name: Twitter
    icon: "fa-brands fa-x-twitter fa-2x"
    weight: 6
    url: "https://twitter.com/anshumant09/"

goatCounter:
  code: "anshumantripathi"

utterances:
  repo: "AnshumanTripathi/anshumantripathi.github.io" # https://utteranc.es/#heading-repository
  issueTerm: "pathname" # https://utteranc.es/#heading-mapping
  label: "blog-comments" # https://utteranc.es/#heading-issue-label
  theme: "preferred-color-scheme" # https://utteranc.es/#heading-theme
