author: "Anshuman Tripathi"
info: "Platform and DevOps Engineering"
description: "Hi, I am Anshuman Tripathi"
keywords: "blog,developer,personal"
colorScheme: "auto"
avatarurl: "images/avatar.png"
favicon_16: "images/avatar.png"
favicon_32: "images/avatar.png"
since: 2023
commit: "https://github.com/AnshumanTripathi/anshumantripathi.github.io/commits/"
license: apache

social:
  - name: Github
    icon: "fa fa-github fa-2x"
    weight: 1
    url: "https://github.com/AnshumanTripathi/"
  - name: Twitter
    icon: "fa fa-twitter fa-2x"
    weight: 2
    url: "https://twitter.com/anshumant09/"
  - name: LinkedIn
    icon: "fa fa-linkedin fa-2x"
    weight: 3
    url: "https://www.linkedin.com/in/anshumantripathi09/"
  - name: Medium
    icon: "fa fa-2x fa-medium"
    weight: 4
    url: "https://medium.com/@anshumantripathi"
  - name: "Mastadon"
    icon: "fa fa-2x fa-mastodon"
    weight: 5
    url: "https://hachyderm.io/@anshuman"
  - name: "buymeacoffee"
    icon: "fa fa-buymeacoffee fa-2x"
    weight: 6
    url: "https://www.buymeacoffee.com/atripathi"

goatCounter:
  code: "anshumantripathi"

utterances:
  repo: "AnshumanTripathi/anshumantripathi.github.io" # https://utteranc.es/#heading-repository
  issueTerm: "pathname" # https://utteranc.es/#heading-mapping
  label: "blog-comments" # https://utteranc.es/#heading-issue-label
  theme: "preferred-color-scheme" # https://utteranc.es/#heading-theme

csp:
  childsrc:
    - 'self'
  fontsrc:
    - 'self'
    - 'https://fonts.gstatic.com'
    - 'https://cdn.jsdelivr.net/'
    - 'https://www.anshumantripathi.com/'
  formaction:
    - 'self'
  framesrc:
    - 'self'
  imgsrc:
    - 'self'
    - 'https://anshumantripathi.goatcounter.com/count'
    - 'https://www.anshumantripathi.com/'
  objectsrc:
    - 'none'
  stylesrc:
    - 'self'
    - 'unsafe-inline'
    - 'https://fonts.googleapis.com/'
    - 'https://fonts.gstatic.com'
    - 'https://cdn.jsdelivr.net/'
    - 'https://www.anshumantripathi.com/'
  scriptsrc:
    - 'self'
    - 'unsafe-inline'
    - 'https://www.google-analytics.com'
    - 'https://gc.zgo.at'
    - 'https://diff.blog'
    - 'https://utteranc.es/'
    - 'https://www.anshumantripathi.com/'
  prefetchsrc:
    - 'self'
  connectsrc:
    - 'self'
    - 'https://www.google-analytics.com'
    - 'https://www.anshumantripathi.com/'
